In [4]:
#Importing libraries
import pandas as pd
import ast

# Bangalore Cars

In [6]:
# Covert excel file to dataframe
path= r"C:\Users\prana\Documents\CarDekho DataSet\bangalore_cars.xlsx"
df_bangalore = pd.read_excel(path)

In [7]:
# top 5 values in the dataframe
df_bangalore.head()
df_bangalore

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [8]:
# size of dataframe
df_bangalore.shape

(1481, 5)

In [9]:
# drop column from dataframe
df_bangalore.drop(columns=["car_links"],inplace=True,axis=1)

In [10]:
df_bangalore

,new_car_detail,new_car_overview,new_car_feature,new_car_specs
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."

# New Car Details

In [11]:
# view new_car_detail
df_bangalore["new_car_detail"]

0       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
4       {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
                              ...
1476    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1477    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
1478    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1479    {'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...
1480    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
Name: new_car_detail, Length: 1481, dtype: object

In [12]:
df_bangalore["new_car_detail"][0]

"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', 'km': '1,20,000', 'transmission': 'Manual', 'ownerNo': 3, 'owner': '3rd Owner', 'oem': 'Maruti', 'model': 'Maruti Celerio', 'modelYear': 2015, 'centralVariantId': 3979, 'variantName': 'VXI', 'price': 'â‚¹ 4 Lakh', 'priceActual': '', 'priceSaving': '', 'priceFixedText': None, 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg', 'heading': 'Trending Car!', 'desc': 'High chances of sale in next 6 days'}}"

In [13]:
# convert string to dict by using Abstract Syntax Trees
df_bangalore["new_car_detail_dict"] = df_bangalore["new_car_detail"].apply(ast.literal_eval)

In [14]:
#flatten the nested dict to dataframe
new_car_detail_blr=pd.json_normalize(df_bangalore["new_car_detail_dict"])
new_car_detail_blr

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,â‚¹ 5.85 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,â‚¹ 4.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,â‚¹ 7.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,2253,4x4 MT,â‚¹ 16.49 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,4257,Zxi BSIII,â‚¹ 3.30 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,1188,S MT,â‚¹ 4.25 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,5695,1.4 Asta Dual Tone,â‚¹ 7.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,1523,Asta Option AT,â‚¹ 6.75 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

# New Car Overview Bangalore

In [15]:
# convert string to dict
df_bangalore["new_car_overview_dict"] = df_bangalore["new_car_overview"].apply(ast.literal_eval)

In [16]:
#flatten the nested dict to dataframe
new_car_overview=pd.json_normalize(df_bangalore["new_car_overview_dict"])
new_car_overview

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': 'Sept 2...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
...,...,...,...
1476,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None
1477,Car overview,"[{'key': 'Registration Year', 'value': 'Jun 20...",None
1478,Car overview,"[{'key': 'Registration Year', 'value': 'Sept 2...",None
1479,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
1480,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None

In [17]:
# drop column from dataframe
new_car_overview.drop(columns=["bottomData"],inplace=True,axis=1)
new_car_overview

           heading                                                top
0     Car overview  [{'key': 'Registration Year', 'value': '2015',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
2     Car overview  [{'key': 'Registration Year', 'value': 'Sept 2...
3     Car overview  [{'key': 'Registration Year', 'value': 'Dec 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2015',...
...            ...                                                ...
1476  Car overview  [{'key': 'Registration Year', 'value': 'May 20...
1477  Car overview  [{'key': 'Registration Year', 'value': 'Jun 20...
1478  Car overview  [{'key': 'Registration Year', 'value': 'Sept 2...
1479  Car overview  [{'key': 'Registration Year', 'value': 'Dec 20...
1480  Car overview  [{'key': 'Registration Year', 'value': 'May 20...

[1481 rows x 2 columns]

In [18]:
new_car_overview["top"][0]

[{'key': 'Registration Year',
  'value': '2015',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'},
 {'key': 'Insurance Validity',
  'value': 'Third Party insurance',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'},
 {'key': 'Fuel Type',
  'value': 'Petrol',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'},
 {'key': 'Seats',
  'value': '5 Seats',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'},
 {'key': 'Kms Driven',
  'value': '1,20,000 Kms',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'},
 {'key': 'RTO',
  'value': 'KA51',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/rto.svg'},
 {'key': 'Ownership',
  'value': 'Third Owner',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'},
 {'key': 'Engine Displacement',
  'value': '998 cc',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'},
 {'key': 'Transmission',
  'value': 'Manual',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'},
 {'key': 'Year of Manufacture',
  'value': 2015,
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}]

In [19]:
# function to get key and value in seperate dict
def extract_key_value_dicts(details):
    if isinstance(details, list):
        return {df['key']: df['value'] for df in details}
    else:
        return {}

In [20]:
# apply function to all values in top column
new_car_overview = new_car_overview['top'].apply(extract_key_value_dicts)
new_car_overview_blr=pd.json_normalize(new_car_overview)

In [21]:
new_car_overview_blr

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2015,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",KA51,Third Owner,998 cc,Manual,2015.0
1,Feb 2018,Comprehensive,Petrol,5 Seats,"32,706 Kms",KA05,Second Owner,1497 cc,Manual,2018.0
2,Sept 2018,Comprehensive,Petrol,5 Seats,"11,949 Kms",KA03,First Owner,1199 cc,Manual,2018.0
3,Dec 2014,Comprehensive,Petrol,5 Seats,"17,794 Kms",KA53,First Owner,1197 cc,Manual,2014.0
4,2015,Third Party insurance,Diesel,5 Seats,"60,000 Kms",KA04,First Owner,1248 cc,Manual,2015.0
...,...,...,...,...,...,...,...,...,...,...
1476,May 2012,Comprehensive,Diesel,7 Seats,"1,56,039 Kms",KA01,Second Owner,2982 cc,Manual,2012.0
1477,Jun 2008,Third Party insurance,Petrol,5 Seats,"56,000 Kms",KA02,Second Owner,1586 cc,Manual,2008.0
1478,Sept 2014,Comprehensive,Petrol,5 Seats,"42,000 Kms",KA03,Second Owner,1198 cc,Manual,2014.0
1479,Dec 2018,Comprehensive,Diesel,5 Seats,"93,003 Kms",KA03,First Owner,1396 cc,Manual,2018.0
1480,May 2017,Comprehensive,Petrol,5 Seats,"36,000 Kms",KA04,Second Owner,1197 cc,Automatic,2017.0

# New car feature Bangalore

In [22]:
# view new_car_feature
df_bangalore["new_car_feature"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1476    {'heading': 'Features', 'top': [{'value': 'Pow...
1477    {'heading': 'Features', 'top': [{'value': 'Pow...
1478    {'heading': 'Features', 'top': [{'value': 'Pow...
1479    {'heading': 'Features', 'top': [{'value': 'Pow...
1480    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature, Length: 1481, dtype: object

In [23]:
# convert string to dict
df_bangalore["new_car_feature_dict"] = df_bangalore["new_car_feature"].apply(ast.literal_eval)

In [24]:
# flatten the nested dict to dataframe
new_car_feature=pd.json_normalize(df_bangalore["new_car_feature_dict"])
new_car_feature

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
1476,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1477,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1478,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1479,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [25]:
# drop column from dataframe
new_car_feature.drop(columns=["commonIcon"],inplace=True,axis=1)
new_car_feature

,heading,top,data
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
...,...,...,...
1476,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1477,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1478,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1479,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."

In [26]:
new_car_feature["top"][0]

[{'value': 'Power Steering'},
 {'value': 'Power Windows Front'},
 {'value': 'Air Conditioner'},
 {'value': 'Heater'},
 {'value': 'Adjustable Head Lights'},
 {'value': 'Manually Adjustable Exterior Rear View Mirror'},
 {'value': 'Centeral Locking'},
 {'value': 'Child Safety Locks'}]

In [27]:
# function to get key and value in seperate dict
def extract_key_value_dicts1(details_1):
    if isinstance(details_1, list):
        return {i: df['value'] for i, df in enumerate(details_1)}
    else:
        return {}

In [28]:
# apply function to all values in top column
new_car_feature_top= new_car_feature["top"].apply(extract_key_value_dicts1)
new_car_feature_top=pd.json_normalize(new_car_feature_top)
new_car_feature_top

,0,1,2,3,4,5,6,7,8
0,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Centeral Locking,Child Safety Locks,NaN
1,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
2,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
3,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
4,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Radio
...,...,...,...,...,...,...,...,...,...
1476,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player
1477,Power Steering,Power Windows Front,Air Conditioner,Heater,Fog Lights Front,Fog Lights Rear,Anti Lock Braking System,Brake Assist,Cd Player
1478,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Centeral Locking,Power Door Locks,Radio
1479,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
1480,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player

In [29]:
new_car_feature["data"][0]

[{'heading': 'Comfort & Convenience',
  'subHeading': 'Comfort',
  'list': [{'value': 'Power Steering'},
   {'value': 'Power Windows Front'},
   {'value': 'Power Windows Rear'},
   {'value': 'Remote Trunk Opener'},
   {'value': 'Remote Fuel Lid Opener'},
   {'value': 'Low Fuel Warning Light'},
   {'value': 'Accessory Power Outlet'},
   {'value': 'Vanity Mirror'},
   {'value': 'Rear Seat Headrest'},
   {'value': 'Cup Holders Front'}]},
 {'heading': 'Interior',
  'subHeading': 'Interior',
  'list': [{'value': 'Air Conditioner'},
   {'value': 'Heater'},
   {'value': 'Digital Odometer'},
   {'value': 'Electronic Multi Tripmeter'},
   {'value': 'Fabric Upholstery'},
   {'value': 'Glove Compartment'},
   {'value': 'Digital Clock'}]},
 {'heading': 'Exterior',
  'subHeading': 'Exterior',
  'list': [{'value': 'Adjustable Head Lights'},
   {'value': 'Manually Adjustable Exterior Rear View Mirror'},
   {'value': 'Wheel Covers'},
   {'value': 'Power Antenna'},
   {'value': 'Chrome Grille'}]},
 {'heading': 'Safety',
  'subHeading': 'Safety',
  'list': [{'value': 'Centeral Locking'},
   {'value': 'Child Safety Locks'},
   {'value': 'Day Night Rear View Mirror'},
   {'value': 'Passenger Side Rear View Mirror'},
   {'value': 'Halogen Headlamps'},
   {'value': 'Rear Seat Belts'},
   {'value': 'Door Ajar Warning'},
   {'value': 'Side Impact Beams'},
   {'value': 'Front Impact Beams'},
   {'value': 'Adjustable Seats'},
   {'value': 'Centrally Mounted Fuel Tank'},
   {'value': 'Engine Immobilizer'},
   {'value': 'Anti Theft Device'}]}]

In [30]:
# flatten the nested dict to dataframe
new_car_feature_data=pd.json_normalize(new_car_feature["data"])
new_car_feature_data

,0,1,2,3,4
0,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...",None
1,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
2,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
3,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
4,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
...,...,...,...,...,...
1476,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1477,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1478,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1479,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1480,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."

In [31]:
# flatten the nested dict to dataframe
new_car_feature_data_1=pd.json_normalize(new_car_feature_data[0])
new_car_feature_data_1

,heading,subHeading,list
0,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
2,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
3,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
4,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
...,...,...,...
1476,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1477,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1478,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1479,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1480,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."

In [32]:
# apply function to all values in list column
new_car_feature_list_1= new_car_feature_data_1["list"].apply(extract_key_value_dicts1)
new_car_feature_list_1=pd.json_normalize(new_car_feature_list_1)
new_car_feature_list_1

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# flatten the nested dict to dataframe
new_car_feature_data_2=pd.json_normalize(new_car_feature_data[1])
new_car_feature_data_2

       heading subHeading                                               list
0     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
2     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
3     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
4     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
...        ...        ...                                                ...
1476  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1477  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1478  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1479  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1480  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...

[1481 rows x 3 columns]

In [34]:
# apply function to all values in list column
new_car_feature_list_2= new_car_feature_data_2["list"].apply(extract_key_value_dicts1)
new_car_feature_list_2=pd.json_normalize(new_car_feature_list_2)
new_car_feature_list_2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Air Conditioner,Heater,Digital Odometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN
2,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN
3,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
4,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
1477,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,NaN,NaN,NaN,NaN
1478,Air Conditioner,Heater,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
1479,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,Dual Tone Dashboard,NaN,NaN,NaN,NaN,NaN
1480,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN

In [35]:
# flatten the nested dict to dataframe
new_car_feature_data_3=pd.json_normalize(new_car_feature_data[2])
new_car_feature_data_3

       heading subHeading                                               list
0     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
2     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
3     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
4     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
...        ...        ...                                                ...
1476  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1477  Exterior   Exterior  [{'value': 'Fog Lights Front'}, {'value': 'Fog...
1478  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1479  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1480  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...

[1481 rows x 3 columns]

In [36]:
# apply function to all values in list column
new_car_feature_list_3= new_car_feature_data_3["list"].apply(extract_key_value_dicts1)
new_car_feature_list_3=pd.json_normalize(new_car_feature_list_3)
new_car_feature_list_3

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Wheel Covers,Power Antenna,Chrome Grille,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Wheel Covers,Power Antenna,Tinted Glass,Rear Spoiler,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Defogger,Alloy Wheels,Power Antenna,Outside Rear View Mirror Turn Indicators,Chrome Grille,Chrome Garnish,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Tinted Glass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Side Stepper,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Alloy Wheels,Tinted Glass,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Wheel Covers,Power Antenna,Chrome Grille,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Rear Spoiler,Outside Rear View Mirror Turn Indicators,Chrome Grille,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Tinted Glass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# flatten the nested dict to dataframe
new_car_feature_data_4=pd.json_normalize(new_car_feature_data[3])
new_car_feature_data_4

     heading subHeading                                               list
0     Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Chi...
1     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
2     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
3     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
4     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
...      ...        ...                                                ...
1476  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1477  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1478  Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Pow...
1479  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1480  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...

[1481 rows x 3 columns]

In [38]:
# apply function to all values in list column
new_car_feature_list_4= new_car_feature_data_4["list"].apply(extract_key_value_dicts1)
new_car_feature_list_4=pd.json_normalize(new_car_feature_list_4)
new_car_feature_list_4

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,Centeral Locking,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Door Ajar Warning,Side Impact Beams,Front Impact Beams,Adjustable Seats,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Door Ajar Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Centeral Locking,Power Door Locks,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Door Ajar Warning,Side Impact Beams,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
# flatten the nested dict to dataframe
new_car_feature_data_5=pd.json_normalize(new_car_feature_data[4])
new_car_feature_data_5

,heading,subHeading,list
0,NaN,NaN,NaN
1,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
2,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
3,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
4,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Audio System R..."
...,...,...,...
1476,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Dvd Player..."
1477,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1478,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1479,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1480,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."

In [40]:
# apply function to all values in list column
new_car_feature_list_5= new_car_feature_data_5["list"].apply(extract_key_value_dicts1)
new_car_feature_list_5=pd.json_normalize(new_car_feature_list_5)
new_car_feature_list_5

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Cd Player,Dvd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Cd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# New Car Specifications Bangalore

In [41]:
# convert string to dict
df_bangalore["new_car_specs_dict"] = df_bangalore["new_car_specs"].apply(ast.literal_eval)

In [42]:
#flatten the nested dict to dataframe
new_car_specs=pd.json_normalize(df_bangalore["new_car_specs_dict"])
new_car_specs

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Mileage', 'value': '23.84 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '19.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Mileage', 'value': '23.65 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
1476,Specifications,"[{'key': 'Mileage', 'value': '12.55 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1477,Specifications,"[{'key': 'Mileage', 'value': '15 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
1478,Specifications,"[{'key': 'Mileage', 'value': '19.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1479,Specifications,"[{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1480,Specifications,"[{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",

In [43]:
# drop column from dataframe
new_car_specs.drop(columns=["commonIcon"],inplace=True,axis=1)
new_car_specs

,heading,top,data
0,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
2,Specifications,"[{'key': 'Mileage', 'value': '23.84 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
3,Specifications,"[{'key': 'Mileage', 'value': '19.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
4,Specifications,"[{'key': 'Mileage', 'value': '23.65 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
...,...,...,...
1476,Specifications,"[{'key': 'Mileage', 'value': '12.55 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1477,Specifications,"[{'key': 'Mileage', 'value': '15 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
1478,Specifications,"[{'key': 'Mileage', 'value': '19.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1479,Specifications,"[{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1480,Specifications,"[{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."

In [44]:
# function to get key and value in seperate dict
def extract_key_value_dicts2(details2):
    if isinstance(details2, list):
        return {df['key']: df['value'] for df in details2}
    else:
        return {}

In [45]:
# apply function to all values in top column
new_car_specs_top_blr= new_car_specs["top"].apply(extract_key_value_dicts2)
new_car_specs_top_blr=pd.json_normalize(new_car_specs_top_blr)
new_car_specs_top_blr

         Mileage   Engine  Max Power    Torque Seats Wheel Size
0      23.1 kmpl   998 CC   67.04bhp      90Nm     5        NaN
1        17 kmpl  1497 CC  121.31bhp     150Nm     5         16
2     23.84 kmpl  1199 CC      84bhp     114Nm     5         14
3      19.1 kmpl  1197 CC   81.86bhp  113.75Nm     5         14
4     23.65 kmpl  1248 CC    88.5bhp     200Nm     5         16
...          ...      ...        ...       ...   ...        ...
1476  12.55 kmpl  2982 CC   168.5bhp     343Nm     7         17
1477     15 kmpl  1586 CC     104.68       145     5         16
1478   19.4 kmpl  1198 CC    86.8bhp     109Nm     5        NaN
1479  22.54 kmpl  1396 CC   88.73bhp   219.7Nm     5         16
1480   18.9 kmpl  1197 CC      82bhp     114Nm     5         14

[1481 rows x 6 columns]

In [46]:
# flatten the nested dict to dataframe
new_car_specs_data=pd.json_normalize(new_car_specs["data"])
new_car_specs_data

,0,1,2
0,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
2,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
3,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
4,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
...,...,...,...
1476,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1477,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1478,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1479,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1480,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."

In [47]:
# flatten the nested dict to dataframe
new_car_specs_data_1=pd.json_normalize(new_car_specs_data[0])
new_car_specs_data_1

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Gray'}, {'key': 'E..."
...,...,...,...
1476,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Blue'}, {'key': 'E..."
1477,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
1478,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
1479,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
1480,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."

In [48]:
# apply function to all values in list column
new_car_specs_list_blr= new_car_specs_data_1["list"].apply(extract_key_value_dicts2)
new_car_specs_list_blr=pd.json_normalize(new_car_specs_list_blr)
new_car_specs_list_blr

,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers
0,White,K10B Engine,998,67.04bhp@6000rpm,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,NaN,NaN,NaN,NaN,NaN
1,White,Ti-VCT Petrol Engine,1497,121.31bhp@6500rpm,150Nm@4500rpm,3.0,4.0,DOHC,Direct Injection,79 X 76.5 mm,11.0:1,No,No,NaN,NaN,NaN,NaN,NaN
2,Red,Revotron Engine,1199,84bhp@6000rpm,114Nm@3500rpm,3.0,4.0,DOHC,MPFi,77 X 85.8 mm,10.8:1,No,No,NaN,NaN,NaN,NaN,NaN
3,Others,Kappa VTVT Petrol Engine,1197,81.86bhp@6000rpm,113.75Nm@4000rpm,4.0,4.0,DOHC,Direct Injection,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN
4,Gray,DDiS 200 Diesel Engine,1248,88.5bhp@4000rpm,200Nm@1750rpm,4.0,4.0,DOHC,NaN,69.6 x 82 mm,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Blue,D-4D Diesel Engine,2982,168.5bhp@3600rpm,343Nm@1400-3400rpm,4.0,4.0,DOHC,CRDi,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
1477,Red,In-Line Engine,1586,"104.68@5,600 (PS@rpm)","145@4,100 (kgm@rpm)",4.0,4.0,DOHC,MPFI,78 x 83 mm,9:01,No,No,NaN,NaN,NaN,NaN,NaN
1478,White,i-VTEC Engine,1198,86.8bhp@6000rpm,109Nm@4500rpm,4.0,4.0,SOHC,PGM - Fi,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN
1479,Red,U2 CRDI Diesel Engine,1396,88.73bhp@4000rpm,219.7Nm@1500-2750rpm,4.0,4.0,DOHC,CRDI,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
1480,White,Kappa VTVT Petrol Engine,1197,82bhp@6000rpm,114Nm@4000rpm,4.0,4.0,DOHC,MPFI,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN

In [49]:
# flatten the nested dict to dataframe
new_car_specs_data_2=pd.json_normalize(new_car_specs_data[1])
new_car_specs_data_2

,heading,subHeading,list
0,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3715mm'}, {'key':..."
1,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3998mm'}, {'key':..."
2,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3746mm'}, {'key':..."
3,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3995mm'}, {'key':..."
4,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4300mm'}, {'key':..."
...,...,...,...
1476,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4705mm'}, {'key':..."
1477,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4490mm'}, {'key':..."
1478,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3610mm'}, {'key':..."
1479,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3985mm'}, {'key':..."
1480,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3765mm'}, {'key':..."

In [50]:
# apply function to all values in list column
new_car_specs_list_2_blr= new_car_specs_data_2["list"].apply(extract_key_value_dicts2)
new_car_specs_list_2_blr=pd.json_normalize(new_car_specs_list_2_blr)
new_car_specs_list_2_blr

,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers
0,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,NaN,NaN,NaN,NaN,NaN,NaN
1,3998mm,1765mm,1647mm,2519mm,NaN,NaN,1242Kg,1660Kg,NaN,NaN,NaN,NaN,NaN,NaN
2,3746mm,1647mm,1535mm,2400mm,1400mm,1420mm,1012kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3995mm,1660mm,1520mm,2425mm,1479mm,1493mm,1180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4300mm,1785mm,1595mm,2600mm,NaN,NaN,1230Kg,1670kg,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,4705mm,1840mm,1850mm,2750mm,1540mm,1540mm,1970kg,2510kg,NaN,NaN,NaN,NaN,NaN,NaN
1477,4490mm,1735mm,1570mm,2500mm,1500mm,1495mm,1200kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,3610mm,1680mm,1500mm,2345mm,1480mm,1465mm,925kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,3985mm,1734mm,1505mm,2570mm,1505mm,1503mm,1515kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,3765mm,1660mm,1520mm,2425mm,1479mm,1493mm,935kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
# flatten the nested dict to dataframe
new_car_specs_data_3=pd.json_normalize(new_car_specs_data[2])
new_car_specs_data_3

,heading,subHeading,list
0,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed '}, {'k..."
1,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
2,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
3,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed '}, {'k..."
4,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
...,...,...,...
1476,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1477,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1478,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1479,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
1480,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '4 Speed'}, {'ke..."

In [52]:
# apply function to all values in list column
new_car_specs_list_3_blr= new_car_specs_data_3["list"].apply(extract_key_value_dicts2)
new_car_specs_list_3_blr=pd.json_normalize(new_car_specs_list_3_blr)
new_car_specs_list_3_blr

,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Alloy Wheel Size
0,5 Speed,FWD,5,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN
1,5 Speed,FWD,5,Power,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16
2,5 Speed,FWD,5,Power,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14
3,5 Speed,FWD,5,Power,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14
4,5 Speed,FWD,5,Power,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,5 Speed,4WD,7,Power,5.9 metres,Ventilated Disc,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5,296-litres,17
1477,5 Speed,NaN,5,Power,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4,505 litres,16
1478,5 Speed,FWD,5,Power,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5,175-litres,NaN
1479,6 Speed,FWD,5,Power,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,5,295-litres,16
1480,4 Speed,FWD,5,Power,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,5,256-liters,14

In [53]:
# concat bangalore car details
df_banglore_cars=pd.concat([new_car_detail_blr,new_car_overview_blr,new_car_specs_top_blr,new_car_specs_list_blr,new_car_specs_list_2_blr,new_car_specs_list_3_blr],axis=1)
df_banglore_cars

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Alloy Wheel Size
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Power,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,Power,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,Power,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,Power,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,Power,5.9 metres,Ventilated Disc,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5,296-litres,17
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,Power,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4,505 litres,16
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,Power,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5,175-litres,NaN
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,Power,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,5,295-litres,16
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,Power,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,5,256-liters,14

In [54]:
#add city column to dataframe
df_banglore_cars['City'] = 'Bangalore'
#final dataframe
df_banglore_cars

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Alloy Wheel Size,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,5.9 metres,Ventilated Disc,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5,296-litres,17,Bangalore
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4,505 litres,16,Bangalore
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5,175-litres,NaN,Bangalore
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,5,295-litres,16,Bangalore
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,5,256-liters,14,Bangalore